"""empty message

Revision ID: 3c90eae75a34
Revises: 
Create Date: 2023-03-05 11:00:07.520795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c90eae75a34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cde_Prods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.Column('produit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cde_prods')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cde_prods',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('commande_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('produit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], name='cde_prods_ibfk_1'),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], name='cde_prods_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Cde_Prods')
    # ### end Alembic commands ###
